# render.yaml

pgbouncer:
  instance_name: minha_instancia_pgbouncer
  host: localhost
  port: 6432
  user: meu_usuario_pgbouncer
  password: meu_password_pgbouncer

databases:
  - name: meu_banco_de_dados
    host: localhost
    port: 5432
    user: meu_usuario_bd
    password: meu_password_bd
